### ISSUE TITLE
Add flag to switch on and off polling logs

### ISSUE THREAD

**Issue by chetakkochrekar** [bormando/gmail-getter#3]
**Description:**
Currently when gmail getter waits for email (until email query is matched) , it generates error logs every time the match fails like below . This creates lots of noise in the console. Is it possible to make this flag based ? Like if the flag for console logs is true then have an option to display custom error message "waiting for email!". If the flag is off then no console logs should be displayed.

version -  "gmail-getter": "^2.1.0",
Automation tool - Playwright 1.30.0
```
{
  "resultSizeEstimate": 0
}
    at fetchEmailsList ()
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at checkInbox ()
    at verifyEmailfromPlatform ()
    at verifyOneCompanyEmail ()
    at 
    at /Users/chetakkochrekar/automationworkspace/ts-new-main-0107/ts-e2e-test/node_modules/@playwright/test/node_modules/playwright/lib/common/testType.js:235:24
    at TestTypeImpl._step (/Users/chetakkochrekar/automationworkspace/ts-new-main-0107/ts-e2e-test/node_modules/@playwright/test/node_modules/playwright/lib/common/testType.js:233:12)
    at /Users/chetakkochrekar/automationworkspace/ts-new-main-0107/ts-e2e-test/tests/pangea/sme/sme-authorisation.spec.ts:94:5
    at /Users/chetakkochrekar/automationworkspace/ts-new-main-0107/ts-e2e-test/node_modules/@playwright/test/node_modules/playwright/lib/worker/workerMain.js:339:9
    at /Users/chetakkochrekar/automationworkspace/ts-new-main-0107/ts-e2e-test/node_modules/@playwright/test/node_modules/playwright/lib/worker/testInfo.js:296:11
    at TimeoutManager.withRunnable (/Users/chetakkochrekar/automationworkspace/ts-new-main-0107/ts-e2e-test/node_modules/@playwright/test/node_modules/playwright/lib/worker/timeoutManager.js:53:14)
    at TestInfoImpl._runAsStage (/Users/chetakkochrekar/automationworkspace/ts-new-main-0107/ts-e2e-test/node_modules/@playwright/test/node_modules/playwright/lib/worker/testInfo.js:294:7)
    at /Users/chetakkochrekar/automationworkspace/ts-new-main-0107/ts-e2e-test/node_modules/@playwright/test/node_modules/playwright/lib/worker/workerMain.js:331:7
    at /Users/chetakkochrekar/automationworkspace/ts-new-main-0107/ts-e2e-test/node_modules/@playwright/test/node_modules/playwright/lib/worker/testInfo.js:296:11
    at TimeoutManager.withRunnable (/Users/chetakkochrekar/automationworkspace/ts-new-main-0107/ts-e2e-test/node_modules/@playwright/test/node_modules/playwright/lib/worker/timeoutManager.js:41:27)
    at TestInfoImpl._runAsStage (/Users/chetakkochrekar/automationworkspace/ts-new-main-0107/ts-e2e-test/node_modules/@playwright/test/node_modules/playwright/lib/worker/testInfo.js:294:7)
    at WorkerMain._runTest (/Users/chetakkochrekar/automationworkspace/ts-new-main-0107/ts-e2e-test/node_modules/@playwright/test/node_modules/playwright/lib/worker/workerMain.js:281:5)
    at WorkerMain.runTestGroup (/Users/chetakkochrekar/automationworkspace/ts-new-main-0107/ts-e2e-test/node_modules/@playwright/test/node_modules/playwright/lib/worker/workerMain.js:205:11)
    at process.<anonymous> (/Users/chetakkochrekar/automationworkspace/ts-new-main-0107/ts-e2e-test/node_modules/@playwright/test/node_modules/playwright/lib/common/process.js:95:22)
```

**Comment by bormando** [comment]
Hi @chetakkochrekar 👋 
Thanks for the suggestion - I'll add it in a new version.

**Comment by bormando** [comment]
I haven't forgotten about that -- a lot of things are going on for me right now.

I think I'll finish this in November/December.

**Comment by chetakkochrekar** [comment]
Thanks for the update @bormando, thats fine no problem!
